### ISSUE TITLE
Rework blue view sdk to be more useful to ROS community

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/installer#11]
Currently, we have our own custom encrypted package which contains the proprietary blueview sdk as well as CMAKE configs so it can work in our catkin build system. It would be better if our blue view driver just depended on the tar file from the blue view CD and not our custom packaging, so the ros community can use it with their tar of the sdk. 

It would work as follows:
* User / script untars bvtsdk and puts it in mil_common/drivers/mil_blueview_driver/
* Once mil_blueview_driver cmake runs, it notices folder is there and build library / driver
* mil_blueview_driver also provides raw bvtsdk library to catkin for use in other ros packages
* if bvtsdk folder is not present, mil_blueview_driver outputs a warning and does not build

This would require a change to the installer and potentially Jenkins:
* Install script should wait until after mil_common has been fetched before downloading bvtsdk
* Install script would only download a encrypted libbvtsdk.tar.gz, not our custom package
* Install script would decrypt, decompress, and untar bvtsdk to mil_common/drivers/mil_blueview_driver
* CI will have to deal with this, will be a PIA

**Comment by sentree** [comment]
This will severely cripple the CI process as it exists now. Since the repositories cannot be cloned during the Docker build process, the SDK can no longer be installed in this stage. The repositories are all currently pulled in the Jenkins file. Since that is version controlled online, the password for the SDK cannot go there. This would mean all Jenkins builds involving the SDK would have to stall for user input and I, personally, do not want to go down that road. So for this to work, you would need to find another way to keep the password off of the repositories.

**Comment by kev-the-dev** [comment]
Alright Mr. Drama. Doesn't seem too hard to fix. If it is running with docker variable true, just decrypt SDK and put it somewhere like .mil. Than jenkins can move it over or symbolic link it when it fetches mil_common.

**Comment by sentree** [comment]
That's a better solution. I was just letting you know it needed fixing with a friendly nudge.

**Comment by sentree** [comment]
This was fixed when #12 was merged.
